spring:
  application:
    name: TP1_Guilda
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  main:
    allow-bean-definition-overriding: true

  elasticsearch:
    uris: http://localhost:9200